name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run make install
      run: make install

    - name: Run make html
      run: make html
      
    - name: Run make pdf
      run: make pdf
