name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Run make install_for_linux
      run: make install_for_linux

    - name: Run make html
      run: make html
      
    - name: Run make pdf
      run: make pdf

  build_mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Run make install_for_mac
      run: make install_for_mac

    - name: Run make html
      run: make html

    - name: Run make pdf
      run: make pdf

